# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fontlengths < Formula
  desc ""
  homepage ""
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arran4/fontlengths/releases/download/v0.0.9/fontlengths_0.0.9_darwin_amd64.tar.gz"
      sha256 "4c52582a1af6a5b31515a71148140ad56f00d8fb1e0d9334b4d19a983920e7ef"

      define_method(:install) do
        bin.install "generate-font-length"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arran4/fontlengths/releases/download/v0.0.9/fontlengths_0.0.9_darwin_arm64.tar.gz"
      sha256 "c6f9ff5bc8ee3305fccbef8dec1bed0cd00cff52fd491564e82f7edc2c502798"

      define_method(:install) do
        bin.install "generate-font-length"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/fontlengths/releases/download/v0.0.9/fontlengths_0.0.9_linux_amd64.tar.gz"
      sha256 "8aa32343a29d75e3211ce5a1b783257672c36a8e9b46bfa66257e25c0f700192"
      define_method(:install) do
        bin.install "generate-font-length"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/fontlengths/releases/download/v0.0.9/fontlengths_0.0.9_linux_armv6.tar.gz"
      sha256 "7fb451a2ebf692393c4e4f9bfd19ba546fb17d11e3b0ea95c3471407a3630abb"
      define_method(:install) do
        bin.install "generate-font-length"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/fontlengths/releases/download/v0.0.9/fontlengths_0.0.9_linux_arm64.tar.gz"
      sha256 "b2b05ae6c2530366f883edacaca92bbbb8c685c65ce18cb42f1d7e52af421bcb"
      define_method(:install) do
        bin.install "generate-font-length"
      end
    end
  end
end
