# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GolangWordwrap < Formula
  desc ""
  homepage ""
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arran4/fontlengths/releases/download/v0.0.8/golang-wordwrap_0.0.8_darwin_amd64.tar.gz"
      sha256 "172827de1487404476a1c26bc274625bf9b7192215bedf030a525d93a7cba2db"

      define_method(:install) do
        bin.install "generate-font-length"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arran4/fontlengths/releases/download/v0.0.8/golang-wordwrap_0.0.8_darwin_arm64.tar.gz"
      sha256 "f998b9d9d4ecf6eed40642857e8654c6039c5d59516072d460946d78e718dbfb"

      define_method(:install) do
        bin.install "generate-font-length"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/fontlengths/releases/download/v0.0.8/golang-wordwrap_0.0.8_linux_amd64.tar.gz"
      sha256 "8a271e8a01fa86ec3b5fdc9f4520b245400ed512ac38eecc20a2247619511c9a"
      define_method(:install) do
        bin.install "generate-font-length"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/fontlengths/releases/download/v0.0.8/golang-wordwrap_0.0.8_linux_armv6.tar.gz"
      sha256 "22a66b279825d6335a2d5d881aab326150823d8c28f1cd409fe2291bfd6cc6c3"
      define_method(:install) do
        bin.install "generate-font-length"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/fontlengths/releases/download/v0.0.8/golang-wordwrap_0.0.8_linux_arm64.tar.gz"
      sha256 "e79a2308ab3148f34b4e32cd74f81a5d207bd6b2f3be49bf8a573a8ff998e68c"
      define_method(:install) do
        bin.install "generate-font-length"
      end
    end
  end
end
