# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GolangDiff < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arran4/golang-diff/releases/download/v0.0.3/golang-diff_darwin_amd64.tar.gz"
      sha256 "e6c3a846ce87782655101db4a79acfdd518bd09dd07f648e971ea818b4a43976"

      define_method(:install) do
        bin.install "diff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arran4/golang-diff/releases/download/v0.0.3/golang-diff_darwin_arm64.tar.gz"
      sha256 "0e179f4130a855619e408a72fcc31a8fbd6293ccf24e847f5877c740b1e277b3"

      define_method(:install) do
        bin.install "diff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/golang-diff/releases/download/v0.0.3/golang-diff_linux_amd64.tar.gz"
      sha256 "88ea835034c1f26c16614d65647c6eaefbecfa23f7871d1d23b2b53c973f984f"
      define_method(:install) do
        bin.install "diff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/golang-diff/releases/download/v0.0.3/golang-diff_linux_arm64.tar.gz"
      sha256 "6a872e3720ec87438bb3cd54ec0e623b54d5f30d703ba0aff5d8ea79f678289e"
      define_method(:install) do
        bin.install "diff"
      end
    end
  end
end
