# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mostcomm < Formula
  desc ""
  homepage ""
  version "1.2.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arran4/mostcomm/releases/download/v1.2.7/mostcomm_1.2.7_darwin_amd64.tar.gz"
      sha256 "ed8e2613c0f4e71e902d39c12c2dedb746d4b08fc6aa7f51b784af620c053508"

      define_method(:install) do
        bin.install "mostcomm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arran4/mostcomm/releases/download/v1.2.7/mostcomm_1.2.7_darwin_arm64.tar.gz"
      sha256 "4031c2c90727dfe0e672ee75b7a883bfdaafa6e75594416a22de1ea60f02208c"

      define_method(:install) do
        bin.install "mostcomm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/mostcomm/releases/download/v1.2.7/mostcomm_1.2.7_linux_amd64.tar.gz"
      sha256 "7338d38c288aabab4c66f45efef103fa9ef3a9d032cb51883b97582175661ea0"
      define_method(:install) do
        bin.install "mostcomm"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/mostcomm/releases/download/v1.2.7/mostcomm_1.2.7_linux_armv6.tar.gz"
      sha256 "61130ca6ddd051051b34a7c6130d64fbb5e6d48eb9abb3aede4e108caad24631"
      define_method(:install) do
        bin.install "mostcomm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/mostcomm/releases/download/v1.2.7/mostcomm_1.2.7_linux_arm64.tar.gz"
      sha256 "19160aba062069468f336e04e2386014a5b9c759ed89e469c1f6e459577c1ea2"
      define_method(:install) do
        bin.install "mostcomm"
      end
    end
  end
end
