# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mostcomm < Formula
  desc ""
  homepage ""
  version "1.2.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arran4/mostcomm/releases/download/v1.2.6/mostcomm_1.2.6_darwin_amd64.tar.gz"
      sha256 "e762f2c6ccd56662871bf12d8f7b077896cb09fe2449eb4a90f21a10c13a281c"

      define_method(:install) do
        bin.install "mostcomm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arran4/mostcomm/releases/download/v1.2.6/mostcomm_1.2.6_darwin_arm64.tar.gz"
      sha256 "e975d04aae2ac9373cc78b406f2af11f3ee4e666478da594a5150592ca97a64b"

      define_method(:install) do
        bin.install "mostcomm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/mostcomm/releases/download/v1.2.6/mostcomm_1.2.6_linux_amd64.tar.gz"
      sha256 "519f41eb19c8cb1ad9e5901391214c868f2be28a6af271980ad2dae816600926"
      define_method(:install) do
        bin.install "mostcomm"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/mostcomm/releases/download/v1.2.6/mostcomm_1.2.6_linux_armv6.tar.gz"
      sha256 "c6b8af00b1ee68fc9d914547f0d9143e6ac8bb98ff58b4d7e72326e2e2bc8b3b"
      define_method(:install) do
        bin.install "mostcomm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/mostcomm/releases/download/v1.2.6/mostcomm_1.2.6_linux_arm64.tar.gz"
      sha256 "1599340cfa1ed8531dc8770f187ee7231c93a7ec52bfad9ba03f738dbb4acb47"
      define_method(:install) do
        bin.install "mostcomm"
      end
    end
  end
end
