# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podcastcdrmanager < Formula
  desc ""
  homepage ""
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v0.0.4/podcastcdrmanager_Darwin_x86_64.tar.gz"
      sha256 "549925dc88e592710ed7cdf638878aa630460a77ae479dbf479a73bdf9075837"

      define_method(:install) do
        bin.install "podcastcdrmanager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v0.0.4/podcastcdrmanager_Darwin_arm64.tar.gz"
      sha256 "a7ab4a2328bcd26a16bbd21fed5c9f6562e5cc57f37db5cf0c62b4748c8817b0"

      define_method(:install) do
        bin.install "podcastcdrmanager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v0.0.4/podcastcdrmanager_Linux_x86_64.tar.gz"
      sha256 "3b796080ca50b5ca8cbcd3516f1bd17e3319f905e924fc25024022957fad7b0d"
      define_method(:install) do
        bin.install "podcastcdrmanager"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v0.0.4/podcastcdrmanager_Linux_armv6.tar.gz"
      sha256 "9c4eae7d59482d6c9787dfb7fac7ecdca2da1cf48f9ec82d6db21dbe9f0f08c0"
      define_method(:install) do
        bin.install "podcastcdrmanager"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v0.0.4/podcastcdrmanager_Linux_arm64.tar.gz"
      sha256 "77b9eee2190d02da3db00f18fab0d602cbd13465dab5a6cb4aaf693fc753b9f0"
      define_method(:install) do
        bin.install "podcastcdrmanager"
      end
    end
  end
end
