# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podcastcdrmanager < Formula
  desc ""
  homepage ""
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v0.0.5/podcastcdrmanager_Darwin_x86_64.tar.gz"
      sha256 "317385cdc3c98a6fe01e5084553179c2fc7fa1472940669c691a927fbf890f3d"

      define_method(:install) do
        bin.install "podcastcdrmanager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v0.0.5/podcastcdrmanager_Darwin_arm64.tar.gz"
      sha256 "4e52b3db8a3b1c5c95d33b9279349585e0fbdb62a51db52a57498758a862bdee"

      define_method(:install) do
        bin.install "podcastcdrmanager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v0.0.5/podcastcdrmanager_Linux_x86_64.tar.gz"
      sha256 "4b16f5694d815e8a9b2572f306fa3cf825997880b18be56a16fa938d5a0b04a4"
      define_method(:install) do
        bin.install "podcastcdrmanager"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v0.0.5/podcastcdrmanager_Linux_armv6.tar.gz"
      sha256 "6bb1655af7cd70c8a826530e8ef53da75072c5396a0f3a3966cf81d155f60180"
      define_method(:install) do
        bin.install "podcastcdrmanager"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v0.0.5/podcastcdrmanager_Linux_arm64.tar.gz"
      sha256 "7ae350875d972358898b385ab9d15706eeba7370b50eb04e80f0b385ce6960ac"
      define_method(:install) do
        bin.install "podcastcdrmanager"
      end
    end
  end
end
