# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rotatingcircles < Formula
  desc ""
  homepage ""
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arran4/rotatingcircles/releases/download/v0.0.4/rotatingcircles_Darwin_x86_64.tar.gz"
      sha256 "5a22a406363228e340da986596716eb72ab6b5c516ed12e56e1dce8b128bde28"

      define_method(:install) do
        bin.install "rotatingcircles"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arran4/rotatingcircles/releases/download/v0.0.4/rotatingcircles_Darwin_arm64.tar.gz"
      sha256 "bc094de2509a54b7b63c4cdd4d3f372d7574489609226a0fd922127c06334f22"

      define_method(:install) do
        bin.install "rotatingcircles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/rotatingcircles/releases/download/v0.0.4/rotatingcircles_Linux_x86_64.tar.gz"
      sha256 "bbd37bdfa0cfc31f3d09400951d37047add4fa5920d0f335b800a893f8f553cb"
      define_method(:install) do
        bin.install "rotatingcircles"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/rotatingcircles/releases/download/v0.0.4/rotatingcircles_Linux_arm64.tar.gz"
      sha256 "d19cf7c2ad980334f34397f5fdebffec47f9dc0e7ccf52eb5b987ea683987de1"
      define_method(:install) do
        bin.install "rotatingcircles"
      end
    end
  end
end
