# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rotatingcircles < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arran4/rotatingcircles/releases/download/v0.0.3/rotatingcircles_Darwin_x86_64.tar.gz"
      sha256 "0d73eb7a5a96f879cdfeefd1f09a67dbbbb4ec980a9fbc6e4b869c1fbd5c7c9d"

      define_method(:install) do
        bin.install "rotatingcircles"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arran4/rotatingcircles/releases/download/v0.0.3/rotatingcircles_Darwin_arm64.tar.gz"
      sha256 "84b4c78f0317b463c96c75d5055d95054ffb9878a4c22143f92002845fef2f73"

      define_method(:install) do
        bin.install "rotatingcircles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/rotatingcircles/releases/download/v0.0.3/rotatingcircles_Linux_x86_64.tar.gz"
      sha256 "5c9cc76e3a7ea00e7baf489ab0a6c1eab165404b000decd8cbd95b4aa45d9601"
      define_method(:install) do
        bin.install "rotatingcircles"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arran4/rotatingcircles/releases/download/v0.0.3/rotatingcircles_Linux_arm64.tar.gz"
      sha256 "57f3637b124a5dabbed2fb044b84a62ce0564a3269db7ef1eb9f44896f96c9b2"
      define_method(:install) do
        bin.install "rotatingcircles"
      end
    end
  end
end
