# This file was generated by GoReleaser. DO NOT EDIT.
cask "barcode-cheatsheets" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "bd024de59518b2b3dd3a350f5748a4540eb1422fd256c862d49079822e6e9443"
      url "https://github.com/arran4/barcode-cheatsheets/releases/download/v#{version}/barcode-cheatsheets_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd86543647208c5c020a3c51eca3dc944d8cc4cc79fb1bb9bd43ae9084ec7b74"
      url "https://github.com/arran4/barcode-cheatsheets/releases/download/v#{version}/barcode-cheatsheets_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "770a4b77bfd32656bf5d7eb24b085bca3e7d97a5e483b007c14ff0242fab39f6"
      url "https://github.com/arran4/barcode-cheatsheets/releases/download/v#{version}/barcode-cheatsheets_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cf4a43cd159bc90ffd28e0ac3bb57f4d6d8049f2be0c6d5726c9a4cd98685520"
      url "https://github.com/arran4/barcode-cheatsheets/releases/download/v#{version}/barcode-cheatsheets_#{version}_linux_arm64.tar.gz"
    end
  end

  name "barcode-cheatsheets"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "barcode-cheatsheets"

  # No zap stanza required

end
