# This file was generated by GoReleaser. DO NOT EDIT.
cask "fontlengths" do
  version "0.0.13"

  on_macos do
    on_intel do
      sha256 "a57d853e199e7178f957d41085f42cb41daf3c085c22c2bca58301da340aaf72"
      url "https://github.com/arran4/fontlengths/releases/download/v#{version}/fontlengths_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8419968f382d18d2b446dff8d51801c90bebfb8d021bc0a77eabecd5522ee045"
      url "https://github.com/arran4/fontlengths/releases/download/v#{version}/fontlengths_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c35e471f4559eeef00c43d3764a773a998e0f24201f07b218b21737ce24225f8"
      url "https://github.com/arran4/fontlengths/releases/download/v#{version}/fontlengths_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "588d249bbd915bc76fc21e41bd3a73d4a4ddc61abe91c41bf970cf4cb65793e6"
      url "https://github.com/arran4/fontlengths/releases/download/v#{version}/fontlengths_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fontlengths"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fontlengths"

  # No zap stanza required

end
