# This file was generated by GoReleaser. DO NOT EDIT.
cask "fontlengths" do
  name "fontlengths"
  desc ""
  homepage ""
  version "0.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fontlengths"

  on_macos do
    on_intel do
      url "https://github.com/arran4/fontlengths/releases/download/v#{version}/fontlengths_#{version}_darwin_amd64.tar.gz"
      sha256 "abd599a7a3482927cedd74bc3d4fd322f5afcb8695b9510e0050d64e5dbda0f1"
    end
    on_arm do
      url "https://github.com/arran4/fontlengths/releases/download/v#{version}/fontlengths_#{version}_darwin_arm64.tar.gz"
      sha256 "e0fd38ba8a8aa8ff79a3b903e9ecc975a18713bdd39aa953417da9b6ed007db0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/fontlengths/releases/download/v#{version}/fontlengths_#{version}_linux_amd64.tar.gz"
      sha256 "b23446f78df1d581f1c59e654c9673d8fa31e2fc26fbe57b43831c43cd09be5a"
    end
    on_arm do
      url "https://github.com/arran4/fontlengths/releases/download/v#{version}/fontlengths_#{version}_linux_arm64.tar.gz"
      sha256 "9775f64ec721ec71e5a7cdf325d0d8aaa662c63c4b5184f15ef5c8ba45fbe9b0"
    end
  end

  # No zap stanza required
end
