# This file was generated by GoReleaser. DO NOT EDIT.
cask "fontlengths" do
  name "fontlengths"
  desc ""
  homepage ""
  version "0.0.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fontlengths"

  on_macos do
    on_intel do
      url "https://github.com/arran4/fontlengths/releases/download/v#{version}/fontlengths_#{version}_darwin_amd64.tar.gz"
      sha256 "d75925b54c9963684baaec71f6921c78c96e5897377a085b8c55f3ee93c4e31a"
    end
    on_arm do
      url "https://github.com/arran4/fontlengths/releases/download/v#{version}/fontlengths_#{version}_darwin_arm64.tar.gz"
      sha256 "fc6dc89af025019963ffd45d3997b71a487121e0ef42fdb9d527b4c9ee44e757"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/fontlengths/releases/download/v#{version}/fontlengths_#{version}_linux_amd64.tar.gz"
      sha256 "2e05e03d5cd5f894ce58aa1fdba824b5cc93c50f4e9b235dde6605f6a8b2c7ba"
    end
    on_arm do
      url "https://github.com/arran4/fontlengths/releases/download/v#{version}/fontlengths_#{version}_linux_arm64.tar.gz"
      sha256 "d1c3ea0bb340f2b9661f8c38624c435126905ca1ba41f7483e2342920da4838b"
    end
  end

  # No zap stanza required
end
