# This file was generated by GoReleaser. DO NOT EDIT.
cask "g2" do
  version "0.0.67"

  on_macos do
    on_intel do
      sha256 "ae50206108cfd417a2aa303fd826dc3714db7b45869f8e8e9126292813864365"
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "589fc57510fc3bfdeb7457d6fd427ff8444b330ebda0342f33c13719ec6fc7d7"
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9936fd1f4337a0936aad48d2ec5a08b7d75e115e99b761f45a3ed8b35d85f38e"
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "61d6efb36b62bd5074f543c963f1cff1fa3fef87f113421eb55f2d112a7050a8"
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_linux_arm64.tar.gz"
    end
  end

  name "g2"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "g2"

  # No zap stanza required

end
