# This file was generated by GoReleaser. DO NOT EDIT.
cask "g2" do
  name "g2"
  desc ""
  homepage ""
  version "0.0.23"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "g2"

  on_macos do
    on_intel do
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_darwin_amd64.tar.gz"
      sha256 "6ca73043bebc23d999e6750efb26a7a1bd5b4b14a7557c1daa7a04832b147272"
    end
    on_arm do
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_darwin_arm64.tar.gz"
      sha256 "454c60f2aec529f0e72760b65558c3d899b6eea67412842fd0e549061398c995"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_linux_amd64.tar.gz"
      sha256 "20df69006ed5096a5d0f9ff6d8e45f8fa9ac0899a1ae14759e4b4356f853637b"
    end
    on_arm do
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_linux_arm64.tar.gz"
      sha256 "4b293281580701f74d3c28f7c38001903fb1e6cd8232a402e62c99a2b04a9239"
    end
  end

  # No zap stanza required
end
