# This file was generated by GoReleaser. DO NOT EDIT.
cask "g2" do
  version "0.0.66"

  on_macos do
    on_intel do
      sha256 "c01d683e3a771f0e13c9af2a6486373b8450b087c18bfd1fb88aeaa257e602f7"
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cd7d3ab575f7dd5c0f7f2cb01e6e050a2941efa941ea6af9068550f0cbc126a1"
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8ead14a7b2f69ca1f4d07f51d584c18f3c07fe9e19bb50b58ac501965a7a90d1"
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "49c72e61f0d789bd92a70f31a1b1fd5494193abb00670dfe018ec37db73594a8"
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_linux_arm64.tar.gz"
    end
  end

  name "g2"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "g2"

  # No zap stanza required

end
