# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-tag-inc" do
  version "1.3.4"

  on_macos do
    on_intel do
      sha256 "ef11941e7d3187fcf527d579ab3d4754d641e41ca4556c48c146e486f14a624c"
      url "https://github.com/arran4/git-tag-inc/releases/download/v#{version}/git-tag-inc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "623d41625c62ffe554501b6405e6e42ff6e0284a96ab5762c878de0f0884d1a3"
      url "https://github.com/arran4/git-tag-inc/releases/download/v#{version}/git-tag-inc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aae9ae013c809eb18ae3accef4ecab8a52c798ccf736d27266855d4da3fa1fb0"
      url "https://github.com/arran4/git-tag-inc/releases/download/v#{version}/git-tag-inc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "314beb543107697ed38bcabf5a036862f2b2b2cf9d8b990f47736e623d776929"
      url "https://github.com/arran4/git-tag-inc/releases/download/v#{version}/git-tag-inc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-tag-inc"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-tag-inc"

  # No zap stanza required

end
