# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-tag-inc" do
  version "1.3.8"

  on_macos do
    on_intel do
      sha256 "acb201048a6b1a7bfd07db4ac7d5dbb7c6fa6a6c92cf7a936870010ce388d9fa"
      url "https://github.com/arran4/git-tag-inc/releases/download/v#{version}/git-tag-inc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bbc6a81685140e574dbca44e1111315b5b2f4a375c69dc6ff9d022991aaba29f"
      url "https://github.com/arran4/git-tag-inc/releases/download/v#{version}/git-tag-inc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3261bcb2e87bcf2648ad66899bf405999904db6a15e81fcf4bb9258054b59d02"
      url "https://github.com/arran4/git-tag-inc/releases/download/v#{version}/git-tag-inc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "31fd367f08dc1ed3642d637830ce613a1c34127e2042bcedc49ec661b56d869b"
      url "https://github.com/arran4/git-tag-inc/releases/download/v#{version}/git-tag-inc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-tag-inc"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-tag-inc"

  # No zap stanza required

end
