# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-tag-inc" do
  version "1.3.2"

  on_macos do
    on_intel do
      url "https://github.com/arran4/git-tag-inc/releases/download/v#{version}/git-tag-inc_#{version}_darwin_amd64.tar.gz"
      sha256 "efa63c0c7512dbae493b0a387160a7c5f2ca1197affaa7b17d3172f998b93e5c"
    end
    on_arm do
      url "https://github.com/arran4/git-tag-inc/releases/download/v#{version}/git-tag-inc_#{version}_darwin_arm64.tar.gz"
      sha256 "7c1a683c44c1ba4ccad91a9cc3b04c3acad1fe6dadd4cd4fc60e3cb9e716c2a7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/git-tag-inc/releases/download/v#{version}/git-tag-inc_#{version}_linux_amd64.tar.gz"
      sha256 "21c8da82895f0fb5f091006e1c9cd04b4298d147d1ee10edb53b0cba20137f06"
    end
    on_arm do
      url "https://github.com/arran4/git-tag-inc/releases/download/v#{version}/git-tag-inc_#{version}_linux_arm64.tar.gz"
      sha256 "85bb1e658cd545871433063a47e58131a372fd4dedc04d59216f02ec6fa2a361"
    end
  end

  name "git-tag-inc"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-tag-inc"

  # No zap stanza required

end
