# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-playerctl" do
  name "go-playerctl"
  desc ""
  homepage ""
  version "0.0.19"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-playerctl"

  on_macos do
    on_intel do
      url "https://github.com/arran4/go-playerctl/releases/download/v#{version}/go-playerctl_#{version}_darwin_amd64.tar.gz"
      sha256 "aefb24513654438bed995cd8f049ac7b5b19d2533fd243397942dc28cf3a26ba"
    end
    on_arm do
      url "https://github.com/arran4/go-playerctl/releases/download/v#{version}/go-playerctl_#{version}_darwin_arm64.tar.gz"
      sha256 "809f7d706b9c6f7a37b3b7a0de2081c12f67c95e9a06072df6002b3a17a87420"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/go-playerctl/releases/download/v#{version}/go-playerctl_#{version}_linux_amd64.tar.gz"
      sha256 "830c0d282d62104d314d076a03865d2084008bca6d7e98ea2330a1a19a4ba155"
    end
    on_arm do
      url "https://github.com/arran4/go-playerctl/releases/download/v#{version}/go-playerctl_#{version}_linux_arm64.tar.gz"
      sha256 "ec9224c350f76b3e1b20a8f0e9167b40cab33552531f599f594d8548bc915adc"
    end
  end

  # No zap stanza required
end
