# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-playerctl" do
  version "0.0.20"

  on_macos do
    on_intel do
      sha256 "73c8de1c93b413b34f96535ba6e36d63fb070196255118de03497a9e77e9e510"
      url "https://github.com/arran4/go-playerctl/releases/download/v#{version}/go-playerctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "60cf9f7b82cea5a9702e53fb685ce6edc4bda25bca2622977ea5e79931d18daf"
      url "https://github.com/arran4/go-playerctl/releases/download/v#{version}/go-playerctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f7e369aabf8b51b0b9c9595b27f24c00b880035f154e758dc5b5ded6efec512b"
      url "https://github.com/arran4/go-playerctl/releases/download/v#{version}/go-playerctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fe02debaa7f63514e3b76dcc849c998623a7934d529be504afe42db85ba2bb84"
      url "https://github.com/arran4/go-playerctl/releases/download/v#{version}/go-playerctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "go-playerctl"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-playerctl"

  # No zap stanza required

end
