# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-playerctl" do
  name "go-playerctl"
  desc ""
  homepage ""
  version "0.0.15"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-playerctl"

  on_macos do
    on_intel do
      url "https://github.com/arran4/go-playerctl/releases/download/v#{version}/go-playerctl_#{version}_darwin_amd64.tar.gz"
      sha256 "ca1c7c1573029101f882cfeb953d686ff0d5efbb92c62897bcb2f47b657a96a7"
    end
    on_arm do
      url "https://github.com/arran4/go-playerctl/releases/download/v#{version}/go-playerctl_#{version}_darwin_arm64.tar.gz"
      sha256 "b0fbcb3916c9dd7830afd82ff95f8173b96337d6d4c20b7b94e835341a2bf199"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/go-playerctl/releases/download/v#{version}/go-playerctl_#{version}_linux_amd64.tar.gz"
      sha256 "57e1bb50c922153347e5209e9cf4c3519f3ef1327dfa66bfbd89e0ecf071c108"
    end
    on_arm do
      url "https://github.com/arran4/go-playerctl/releases/download/v#{version}/go-playerctl_#{version}_linux_arm64.tar.gz"
      sha256 "dd74c324dbe10ad525b704a35479a2d247c47e5f3f12729eddf69a09d6cff7e6"
    end
  end

  # No zap stanza required
end
