# This file was generated by GoReleaser. DO NOT EDIT.
cask "golang-diff" do
  name "golang-diff"
  desc ""
  homepage ""
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "golang-diff"

  on_macos do
    on_intel do
      url "https://github.com/arran4/golang-diff/releases/download/v#{version}/golang-diff_darwin_amd64.tar.gz"
      sha256 "388d6bc8a68d0559e905719fd9e0cd2cc112f1b1362c9347e83b0fd02a8bf9a2"
    end
    on_arm do
      url "https://github.com/arran4/golang-diff/releases/download/v#{version}/golang-diff_darwin_arm64.tar.gz"
      sha256 "93e6a971405b415127eb2dc965d1c9c7af451f14dcf899d25efdbd542c07ff30"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/golang-diff/releases/download/v#{version}/golang-diff_linux_amd64.tar.gz"
      sha256 "47898c55dae4f32c223f7e9641bbcdd0fb79e207b761b6aac909964c9172f1e1"
    end
    on_arm do
      url "https://github.com/arran4/golang-diff/releases/download/v#{version}/golang-diff_linux_arm64.tar.gz"
      sha256 "1eef17900295142ef0542779e0c9fdee8a57a3bda050a40ae066f17c88d3a20f"
    end
  end

  # No zap stanza required
end
