# This file was generated by GoReleaser. DO NOT EDIT.
cask "golang-diff" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "b09ba37874dae4d0766c7309ff6619162dd379ac6641103db84848cde24a3374"
      url "https://github.com/arran4/golang-diff/releases/download/v#{version}/golang-diff_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "26552912c1597bd2ee824fba7144a2ca92f98836d8377dd971c0bf25fa826795"
      url "https://github.com/arran4/golang-diff/releases/download/v#{version}/golang-diff_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4601f0bf53065e038540225211cee24632ce6e2acef024a5d912fc9e9fad6ba3"
      url "https://github.com/arran4/golang-diff/releases/download/v#{version}/golang-diff_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cdde00ae11825631b9d392141dae36d2351bf50eda9cedcf7d74af4c5705c288"
      url "https://github.com/arran4/golang-diff/releases/download/v#{version}/golang-diff_linux_arm64.tar.gz"
    end
  end

  name "golang-diff"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "golang-diff"

  # No zap stanza required

end
