# This file was generated by GoReleaser. DO NOT EDIT.
cask "golang-diff" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "9c2920db2c42e72d9c94c54038958e24334da90c7793f884f73b5c54b69f18f7"
      url "https://github.com/arran4/golang-diff/releases/download/v#{version}/golang-diff_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "860e19256880b8bfe7a68d584ae6aadcd2f56f1e2378d625527b4ad014328fac"
      url "https://github.com/arran4/golang-diff/releases/download/v#{version}/golang-diff_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1174845afa73485c6eee7c31b064cf75cc0529a9cb8ade4cc48adeb650860c28"
      url "https://github.com/arran4/golang-diff/releases/download/v#{version}/golang-diff_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0373179a919f85043b44675ef89f5842f47ed0375f3828524f19d4e8c09b19c1"
      url "https://github.com/arran4/golang-diff/releases/download/v#{version}/golang-diff_linux_arm64.tar.gz"
    end
  end

  name "golang-diff"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "golang-diff"

  # No zap stanza required

end
