# This file was generated by GoReleaser. DO NOT EDIT.
cask "gosubc" do
  version "0.0.24"

  on_macos do
    on_intel do
      sha256 "5a69042ff8cc462af037703010ef9854a4b9cd8bae5f665db27e7b6145c1bcb9"
      url "https://github.com/arran4/go-subcommand/releases/download/v#{version}/gosubc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d33b35d9c84a9e194137788060bc230626f663f2470f1ef09f158d3eba0624f"
      url "https://github.com/arran4/go-subcommand/releases/download/v#{version}/gosubc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "451b6081a9e1fa3031193c5acd594164152a13a5a62e76a7be4bf49786cee519"
      url "https://github.com/arran4/go-subcommand/releases/download/v#{version}/gosubc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fed3816f579deccc6fbb1bb4c826568abb8e4c45ef34d4b31b55f61467a1df4a"
      url "https://github.com/arran4/go-subcommand/releases/download/v#{version}/gosubc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gosubc"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gosubc"

  # No zap stanza required

end
