# This file was generated by GoReleaser. DO NOT EDIT.
cask "gosubc" do
  version "0.0.30"

  on_macos do
    on_arm do
      sha256 "f83d8d31092b641c07548b977bc8288f0a9fd45742de0c82e62d3426b54c71b2"
      url "https://github.com/arran4/go-subcommand/releases/download/v#{version}/gosubc_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9f1d287d93af6c695bd77c09c052d85a1895930eae812fdc22d6c1ee11517cc"
      url "https://github.com/arran4/go-subcommand/releases/download/v#{version}/gosubc_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "575d02ad35f8bc95679bf94bf6d6e139d59a0c1f0c13fbf64f99fcb0a3a2bb16"
      url "https://github.com/arran4/go-subcommand/releases/download/v#{version}/gosubc_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2069bb67c91207b766142ecc4467c3d298a5b5fc1e9410ea2bdfd862eaf548e5"
      url "https://github.com/arran4/go-subcommand/releases/download/v#{version}/gosubc_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gosubc"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gosubc"

  # No zap stanza required
end
