# This file was generated by GoReleaser. DO NOT EDIT.
cask "gosubc" do
  version "0.0.23"

  on_macos do
    on_intel do
      sha256 "0d1140e8577aeb9cac18f5c306a62c34ad5720c5706549389d0d90977a113f48"
      url "https://github.com/arran4/go-subcommand/releases/download/v#{version}/gosubc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c6f94d7cdf85fec73e48be748fa1f417df64ede7d4732a20e2fefc31e2638f46"
      url "https://github.com/arran4/go-subcommand/releases/download/v#{version}/gosubc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3155aa339b33641a4b0a818744dc3f63a92277ef21f63bd5109b9b81de99e537"
      url "https://github.com/arran4/go-subcommand/releases/download/v#{version}/gosubc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "061bc34a74cd8e155a06d21b3d2f05095f19eddf40a39e83764f50dfe088836b"
      url "https://github.com/arran4/go-subcommand/releases/download/v#{version}/gosubc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gosubc"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gosubc"

  # No zap stanza required

end
