# This file was generated by GoReleaser. DO NOT EDIT.
cask "mostcomm" do
  name "mostcomm"
  desc ""
  homepage ""
  version "1.2.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mostcomm"

  on_macos do
    on_intel do
      url "https://github.com/arran4/mostcomm/releases/download/v#{version}/mostcomm_#{version}_darwin_amd64.tar.gz"
      sha256 "3ba5026d8dc3d991523cf49bee30d6eccd9dc23fb25b81de9d57c5ecf217819c"
    end
    on_arm do
      url "https://github.com/arran4/mostcomm/releases/download/v#{version}/mostcomm_#{version}_darwin_arm64.tar.gz"
      sha256 "13cf582462ceed863ea79e128e9caf6f8c9a9b4c730e4d968e51e0dd0bf79f2f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/mostcomm/releases/download/v#{version}/mostcomm_#{version}_linux_amd64.tar.gz"
      sha256 "b6943745d16118126624ae726756cc533def9266428492942c328e81aff44f5d"
    end
    on_arm do
      url "https://github.com/arran4/mostcomm/releases/download/v#{version}/mostcomm_#{version}_linux_arm64.tar.gz"
      sha256 "d8018c9892479962395e8843cbfa732be6f1e1db67e0edfa4547981f7d5d30fa"
    end
  end

  # No zap stanza required
end
