# This file was generated by GoReleaser. DO NOT EDIT.
cask "mostcomm" do
  name "mostcomm"
  desc ""
  homepage ""
  version "1.2.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mostcomm"

  on_macos do
    on_intel do
      url "https://github.com/arran4/mostcomm/releases/download/v#{version}/mostcomm_#{version}_darwin_amd64.tar.gz"
      sha256 "6224f443afb4117c079b130f5021946db67c5bf13dcf7c5d4d02a0a2e55d7456"
    end
    on_arm do
      url "https://github.com/arran4/mostcomm/releases/download/v#{version}/mostcomm_#{version}_darwin_arm64.tar.gz"
      sha256 "d8c79cc506d5f072a035bdf15e5c9ce362c4d93afaa40142509b381a4960afc1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/mostcomm/releases/download/v#{version}/mostcomm_#{version}_linux_amd64.tar.gz"
      sha256 "702abe2b5cb74609fffc102adb5115007c09bae7ec4e544a166a1a39100de9f7"
    end
    on_arm do
      url "https://github.com/arran4/mostcomm/releases/download/v#{version}/mostcomm_#{version}_linux_arm64.tar.gz"
      sha256 "41addf908bf14ae813fa36b6298059b683156569cfc4fd2ab963d449bb61ab93"
    end
  end

  # No zap stanza required
end
