# This file was generated by GoReleaser. DO NOT EDIT.
cask "mostcomm" do
  name "mostcomm"
  desc ""
  homepage ""
  version "1.2.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mostcomm"

  on_macos do
    on_intel do
      url "https://github.com/arran4/mostcomm/releases/download/v#{version}/mostcomm_#{version}_darwin_amd64.tar.gz"
      sha256 "0abb3b881460c5c450a6b993906dc4c69eec887a774e0be9b7664d5cb9f35a42"
    end
    on_arm do
      url "https://github.com/arran4/mostcomm/releases/download/v#{version}/mostcomm_#{version}_darwin_arm64.tar.gz"
      sha256 "df678c2c252e8a18866daaa2266d192d8609a16d5ade95126f8bf82f5b8679c2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/mostcomm/releases/download/v#{version}/mostcomm_#{version}_linux_amd64.tar.gz"
      sha256 "ea80d3a2c2aa1e5f66f90a931e592b055bd0c012b34e8abe3606d1a8d193ef4d"
    end
    on_arm do
      url "https://github.com/arran4/mostcomm/releases/download/v#{version}/mostcomm_#{version}_linux_arm64.tar.gz"
      sha256 "d6cc6eda30d1fe67c38e9f877a28171d7821bf685a44d56abf26dc2dc64b06bd"
    end
  end

  # No zap stanza required
end
