# This file was generated by GoReleaser. DO NOT EDIT.
cask "mvcommon" do
  name "mvcommon"
  desc ""
  homepage ""
  version "1.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mvcommon"

  on_macos do
    on_intel do
      url "https://github.com/arran4/mvcommon/releases/download/v#{version}/mvcommon_#{version}_darwin_amd64.tar.gz"
      sha256 "532655b91a49957bd82831cc680635124b43a01d24ec83a3ca67eaea0abfcbf1"
    end
    on_arm do
      url "https://github.com/arran4/mvcommon/releases/download/v#{version}/mvcommon_#{version}_darwin_arm64.tar.gz"
      sha256 "67ce7ac0d07227456408e217b9ae9ce9773baa7f4f5c9aacbf2f2bdfcb51ad30"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/mvcommon/releases/download/v#{version}/mvcommon_#{version}_linux_amd64.tar.gz"
      sha256 "1b1742bd3a51a1d45a019713917bdbc3367e50163a3573a3592dd6597f3f4332"
    end
    on_arm do
      url "https://github.com/arran4/mvcommon/releases/download/v#{version}/mvcommon_#{version}_linux_arm64.tar.gz"
      sha256 "86b8fb829455cc7ca2f4b74a122601be9a3792a9629220f6d49e6f1e87f547e3"
    end
  end

  # No zap stanza required
end
