# This file was generated by GoReleaser. DO NOT EDIT.
cask "mvcommon" do
  version "1.0.9"

  on_macos do
    on_arm do
      sha256 "f075df176afa863ca10f227de4da8bcce6d00a89abd222f679362a1f22bf4b5d"
      url "https://github.com/arran4/mvcommon/releases/download/v#{version}/mvcommon_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6eca9c8eb54785cf6e6394372e664a7b3dd62bf77fa71a249d6ee3d2fde1fe05"
      url "https://github.com/arran4/mvcommon/releases/download/v#{version}/mvcommon_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1a81d8d480190234b15b9527647bd85f1a6f4d844f356e4e5ac61f855083dae9"
      url "https://github.com/arran4/mvcommon/releases/download/v#{version}/mvcommon_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "489590234b8b7901f0387d4c6e387310f1e0e71a4adf0402ec48a5dd2cee424a"
      url "https://github.com/arran4/mvcommon/releases/download/v#{version}/mvcommon_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mvcommon"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mvcommon"

  # No zap stanza required
end
