# This file was generated by GoReleaser. DO NOT EDIT.
cask "phonenumber" do
  version "1.0.13"

  on_macos do
    on_intel do
      sha256 "a02d2f79034cbd6a1a43e30a37a8f81d141c8495573b0eb04375bf58216ed244"
      url "https://github.com/arran4/phonenumber/releases/download/v#{version}/phonenumber_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "37d4f0d879172ac4d2221c457cd60b4e90f0a6ca5060ebff9c64884e14193fc2"
      url "https://github.com/arran4/phonenumber/releases/download/v#{version}/phonenumber_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "383de113a9cf69b76fd37c23f985b4bf9acdf5792f8d6bec837193dfacc58ca5"
      url "https://github.com/arran4/phonenumber/releases/download/v#{version}/phonenumber_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "14786acc5d37f62110933672167322d5e6b619108b1d0ac384a53c1554737ce1"
      url "https://github.com/arran4/phonenumber/releases/download/v#{version}/phonenumber_#{version}_linux_arm64.tar.gz"
    end
  end

  name "phonenumber"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phonenumber"

  # No zap stanza required

end
