# This file was generated by GoReleaser. DO NOT EDIT.
cask "phonenumber" do
  version "1.0.14"

  on_macos do
    on_arm do
      sha256 "18809b6721ad80bc5e4baf5a787072a34a369600d55c1d261c27aef4f1b18558"
      url "https://github.com/arran4/phonenumber/releases/download/v#{version}/phonenumber_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d196c8dcfd5e3e4f5a1f0625e69e4369c777f00a51d07e84460b3771950be202"
      url "https://github.com/arran4/phonenumber/releases/download/v#{version}/phonenumber_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5bc159c57695f50eb689878f16729a8f35a81a8921c7900af12c9370667634db"
      url "https://github.com/arran4/phonenumber/releases/download/v#{version}/phonenumber_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "47813063daead30cb8b35b63dbd75064d3cfd317f68a9bd58e72ea63d8e1e755"
      url "https://github.com/arran4/phonenumber/releases/download/v#{version}/phonenumber_#{version}_linux_amd64.tar.gz"
    end
  end

  name "phonenumber"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phonenumber"

  # No zap stanza required
end
