# This file was generated by GoReleaser. DO NOT EDIT.
cask "phonenumber" do
  name "phonenumber"
  desc ""
  homepage ""
  version "1.0.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phonenumber"

  on_macos do
    on_intel do
      url "https://github.com/arran4/phonenumber/releases/download/v#{version}/phonenumber_#{version}_darwin_amd64.tar.gz"
      sha256 "9799aa11cbb524a577054eac8bad14249d71e0d35bd6e9b83586532fce1e70e6"
    end
    on_arm do
      url "https://github.com/arran4/phonenumber/releases/download/v#{version}/phonenumber_#{version}_darwin_arm64.tar.gz"
      sha256 "b0a9e192284ba40461dc310b2580e97866d83bede92a23461e1b6035799f9305"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/phonenumber/releases/download/v#{version}/phonenumber_#{version}_linux_amd64.tar.gz"
      sha256 "77fdc64651198d8075fd4e6f645cabc2b39a4bad264ed766798457afddc9f9b7"
    end
    on_arm do
      url "https://github.com/arran4/phonenumber/releases/download/v#{version}/phonenumber_#{version}_linux_arm64.tar.gz"
      sha256 "03b0bf775205a89891d42294534fc8c484f2c454769fda5e4e4f79521336cd51"
    end
  end

  # No zap stanza required
end
