# This file was generated by GoReleaser. DO NOT EDIT.
cask "podcastcdrmanager" do
  name "podcastcdrmanager"
  desc ""
  homepage ""
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "podcastcdrmanager"

  on_macos do
    on_intel do
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v#{version}/podcastcdrmanager_Darwin_x86_64.tar.gz"
      sha256 "80de211af8b999362f70651c7fc57eb957456cbdec9a41a4a685d8e11522d292"
    end
    on_arm do
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v#{version}/podcastcdrmanager_Darwin_arm64.tar.gz"
      sha256 "de936cbcff7cd948e35ec21a11c734052ff9bf2d79972fcd03ed4c64f6499a4f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v#{version}/podcastcdrmanager_Linux_x86_64.tar.gz"
      sha256 "7803a47c79a878d3979aefe1fbb8ee1e5df3173af0e15f0f34aab2fe5dcb03ce"
    end
    on_arm do
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v#{version}/podcastcdrmanager_Linux_arm64.tar.gz"
      sha256 "7107cfa70ca05ca09b2a37d1ed082a7e365f00695ccb179733f825e445cc4dbc"
    end
  end

  # No zap stanza required
end
