# This file was generated by GoReleaser. DO NOT EDIT.
cask "podcastcdrmanager" do
  version "0.0.9"

  on_macos do
    on_intel do
      sha256 "a4eea54c46da687ddf0d5f72fb9ea812a72810cb9204e2fbaaf643d33508aa29"
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v#{version}/podcastcdrmanager_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b083cec391b51a0530c7a05838862034c62f790f25f89bcb9e8a1281e91686c0"
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v#{version}/podcastcdrmanager_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c7bd5022ec4c6144c7c9cd706066fe866aa63e5242135ce2cacc07b57fcd3bc1"
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v#{version}/podcastcdrmanager_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2e8a774684866cdcbfe8cb1b41bd57b7719eb5aa7caed2fecad4fdf2986bf4f2"
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v#{version}/podcastcdrmanager_#{version}_linux_arm64.tar.gz"
    end
  end

  name "podcastcdrmanager"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "podcastcdrmanager"

  # No zap stanza required

end
