# This file was generated by GoReleaser. DO NOT EDIT.
cask "podcastcdrmanager" do
  version "0.0.8"

  on_macos do
    on_intel do
      sha256 "a0853000779cd1b35452fa242cafe7762c0b1a9abb3a85f3edcdafc6b5485dd9"
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v#{version}/podcastcdrmanager_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7842853897b2bd6eab9dae06526f879e98657695f69eb691b4db3bf6465b2fd9"
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v#{version}/podcastcdrmanager_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3d670a9fc07f8ca5465193e5aa7bcb72aed1ad822b8d592ff5e501d5ad1d69f2"
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v#{version}/podcastcdrmanager_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f169f256172fae2158ab02048a3f0f67fac56084478456654cf8c7a1272fff7"
      url "https://github.com/arran4/podcast-cdr-manager/releases/download/v#{version}/podcastcdrmanager_#{version}_linux_arm64.tar.gz"
    end
  end

  name "podcastcdrmanager"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "podcastcdrmanager"

  # No zap stanza required

end
