# This file was generated by GoReleaser. DO NOT EDIT.
cask "qip" do
  name "qip"
  desc "qip - Image Processing CLI"
  homepage "https://github.com/royalicing/qip"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qip"

  on_macos do
    on_intel do
      url "https://github.com/arran4/fork-qip/releases/download/v#{version}/qip_Darwin_x86_64.tar.gz"
      sha256 "9eaffd92d7d7abe70155ada806edf1dcd9d00a8743802e3a6372b9eaedaa2b78"
    end
    on_arm do
      url "https://github.com/arran4/fork-qip/releases/download/v#{version}/qip_Darwin_arm64.tar.gz"
      sha256 "ab40f75d009bd8f397a09f0731ee69818fa6afc6499d95df289f76e009267ca3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/fork-qip/releases/download/v#{version}/qip_Linux_x86_64.tar.gz"
      sha256 "3928b4fb7ab10ea547d70a3f8a1aa6d52f8c380254223d0b2264f298d243575b"
    end
    on_arm do
      url "https://github.com/arran4/fork-qip/releases/download/v#{version}/qip_Linux_arm64.tar.gz"
      sha256 "a8ad1e064f7c17e90c8f4462c28bcdfe80232defa9a5fa07f86771cf7cd9377e"
    end
  end

  # No zap stanza required
end
