# This file was generated by GoReleaser. DO NOT EDIT.
cask "qip" do
  name "qip"
  desc "qip - Image Processing CLI"
  homepage "https://github.com/royalicing/qip"
  version "0.0.15"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qip"

  on_macos do
    on_intel do
      url "https://github.com/arran4/fork-qip/releases/download/v#{version}/qip_Darwin_x86_64.tar.gz"
      sha256 "aa708d204b0890168eaeb0a1ee6440dd48771ef0eb2f422413143ccc87bcd2f2"
    end
    on_arm do
      url "https://github.com/arran4/fork-qip/releases/download/v#{version}/qip_Darwin_arm64.tar.gz"
      sha256 "a1d0d7f68b381d2607d787394f24c21781acd3b3c29fa83d23bbed4c0a0ffc79"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/fork-qip/releases/download/v#{version}/qip_Linux_x86_64.tar.gz"
      sha256 "19d160ad25d83c3eff94d9602dbbdb785e4e7013e85aa799505ad123a8dafec0"
    end
    on_arm do
      url "https://github.com/arran4/fork-qip/releases/download/v#{version}/qip_Linux_arm64.tar.gz"
      sha256 "7b35e172aba4fecf8d65c10b8e3d7c2f2ebd8449541be117500910c41282a18e"
    end
  end

  # No zap stanza required
end
