# This file was generated by GoReleaser. DO NOT EDIT.
cask "qip" do
  name "qip"
  desc "qip - Image Processing CLI"
  homepage "https://github.com/royalicing/qip"
  version "0.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qip"

  on_macos do
    on_intel do
      url "https://github.com/arran4/fork-qip/releases/download/v#{version}/qip_Darwin_x86_64.tar.gz"
      sha256 "6d3d9fc210d5167d752b881904089f920e38af8fd9c358beb8e46cdb5c6d26c0"
    end
    on_arm do
      url "https://github.com/arran4/fork-qip/releases/download/v#{version}/qip_Darwin_arm64.tar.gz"
      sha256 "21a94a40482ae7a2b74c2795fb451b3640a6a103321b23f5582682c2c759897b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/fork-qip/releases/download/v#{version}/qip_Linux_x86_64.tar.gz"
      sha256 "4cf66802b64a8d5d77b1de6d01858d96fc7e32c9d0679ab61c2afdac20338e9f"
    end
    on_arm do
      url "https://github.com/arran4/fork-qip/releases/download/v#{version}/qip_Linux_arm64.tar.gz"
      sha256 "cdf9e09c4904396752a0776fe7aa3ac7fd9e8f999a598a44c0cfa9d22c39116e"
    end
  end

  # No zap stanza required
end
