# This file was generated by GoReleaser. DO NOT EDIT.
cask "rntocase" do
  name "rntocase"
  desc ""
  homepage ""
  version "0.1.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rntocase"

  on_macos do
    on_intel do
      url "https://github.com/arran4/rntocase/releases/download/v#{version}/rntocase_#{version}_darwin_amd64.tar.gz"
      sha256 "e8ecb8536ed7c0bba572d2b00d750b2ded70a604006bfb0044abdb31978a6851"
    end
    on_arm do
      url "https://github.com/arran4/rntocase/releases/download/v#{version}/rntocase_#{version}_darwin_arm64.tar.gz"
      sha256 "11fbee6364983eb9589358dbb93fd1da4efd6712019c76d083575d810273c748"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/rntocase/releases/download/v#{version}/rntocase_#{version}_linux_amd64.tar.gz"
      sha256 "6aeebc946f07897bfa3972801413225f3907938ebd90df029c3f00088803aaeb"
    end
    on_arm do
      url "https://github.com/arran4/rntocase/releases/download/v#{version}/rntocase_#{version}_linux_arm64.tar.gz"
      sha256 "dd04f8873c14de1f3834a279fea50f3668fb8028fc00e05e23dbd6d1e5e06019"
    end
  end

  # No zap stanza required
end
