# This file was generated by GoReleaser. DO NOT EDIT.
cask "rntocase" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "d17afb466181fade2237740e1a5ee4a247d158a426e8188dfe0b77870128eb34"
      url "https://github.com/arran4/rntocase/releases/download/v#{version}/rntocase_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "af6cb0923d1fe64ceb702ed823174f09d6a53790f64cd0e9e3a59c315bdffa70"
      url "https://github.com/arran4/rntocase/releases/download/v#{version}/rntocase_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ab28717b563c2bfa093425efdd3424c0f2f3bf2f5e3eb7dc8545a0d70ab163b3"
      url "https://github.com/arran4/rntocase/releases/download/v#{version}/rntocase_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ae52c390779f3fa914b718693d0b9385b9062794ebd8c85df24df4dc4dc358f6"
      url "https://github.com/arran4/rntocase/releases/download/v#{version}/rntocase_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rntocase"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rntocase"

  # No zap stanza required
end
