# This file was generated by GoReleaser. DO NOT EDIT.
cask "rntocase" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "21af88cd20316c0fbd281d38a7998ce820c2113bba7c54aa9127026659bb04f1"
      url "https://github.com/arran4/rntocase/releases/download/v#{version}/rntocase_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "88807396d64260110eb0a8b32f6a4eb5e5f76bf0ead600fdfc20bc11bef50bd5"
      url "https://github.com/arran4/rntocase/releases/download/v#{version}/rntocase_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8902713032a5d20d63c06fb6001bec86490483e49c7c1689f163e862e299d291"
      url "https://github.com/arran4/rntocase/releases/download/v#{version}/rntocase_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c3fc76697dbadb7a61e6cde1699054ec23a44065c398792a732ab8b25bf0f337"
      url "https://github.com/arran4/rntocase/releases/download/v#{version}/rntocase_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rntocase"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rntocase"

  # No zap stanza required
end
