# This file was generated by GoReleaser. DO NOT EDIT.
cask "rotatingcircles" do
  version "0.0.8"

  on_macos do
    on_intel do
      sha256 "88ab2dd560789cd1b7f9599a3fa73e7165ec1e3c3b6bb9caeea28ece996d56e2"
      url "https://github.com/arran4/rotatingcircles/releases/download/v#{version}/rotatingcircles_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "277cdab7661c4576f720e462069179f36a08cfbd484e16db6a2616538ca19679"
      url "https://github.com/arran4/rotatingcircles/releases/download/v#{version}/rotatingcircles_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1ffe041c78524011c63d67520ef516fe641c13a80b2dc59e18080e7e69e8ca9d"
      url "https://github.com/arran4/rotatingcircles/releases/download/v#{version}/rotatingcircles_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e93527423dc7da78dc9f26d25f367ccab341f56ebb35d1176749fe894ff3bf9f"
      url "https://github.com/arran4/rotatingcircles/releases/download/v#{version}/rotatingcircles_Linux_arm64.tar.gz"
    end
  end

  name "rotatingcircles"
  desc "Generates an optical illusion: Rotating circles"
  homepage "https://github.com/arran4/rotatingcircles"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rotatingcircles"

  # No zap stanza required

end
