# This file was generated by GoReleaser. DO NOT EDIT.
cask "rotatingcircles" do
  name "rotatingcircles"
  desc ""
  homepage ""
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rotatingcircles"

  on_macos do
    on_intel do
      url "https://github.com/arran4/rotatingcircles/releases/download/v#{version}/rotatingcircles_Darwin_x86_64.tar.gz"
      sha256 "05ed9ceafdcae068b4b8f25b7c38be0722631dca4ec133616f4c6548c0c684d9"
    end
    on_arm do
      url "https://github.com/arran4/rotatingcircles/releases/download/v#{version}/rotatingcircles_Darwin_arm64.tar.gz"
      sha256 "0f56501b8a3c8ca9f8f89682cd7c16037568abdcf12ca3a758c746bdd6f1bdfe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/rotatingcircles/releases/download/v#{version}/rotatingcircles_Linux_x86_64.tar.gz"
      sha256 "ee955e2823b71ddf49c597d8b53a270af2b0731fd95bf2a1dee94b1c5d29d6b2"
    end
    on_arm do
      url "https://github.com/arran4/rotatingcircles/releases/download/v#{version}/rotatingcircles_Linux_arm64.tar.gz"
      sha256 "f56aeeeb680713414cf50638c7d0993210210fdbd84a808dadb27a4b2b9b7d81"
    end
  end

  # No zap stanza required
end
