# This file was generated by GoReleaser. DO NOT EDIT.
cask "rotatingcircles" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "88e1db04c19c918e43d7a51e391f152f9f45ac7a6601cf7e3bbd5d76c86f13ed"
      url "https://github.com/arran4/rotatingcircles/releases/download/v#{version}/rotatingcircles_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8ed3b2d2a44043fc8a8f78490556a878ee13697c69a61218ff0e1290d4b2c818"
      url "https://github.com/arran4/rotatingcircles/releases/download/v#{version}/rotatingcircles_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a5b066cb22ecbf7499bdd9d7ee965f4bc120b41d8bc0c8cf7a6fac7064f515d7"
      url "https://github.com/arran4/rotatingcircles/releases/download/v#{version}/rotatingcircles_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2baaf7ffdd25c5ac04c2c146643e8fc70f021c2457f86352b1aa049a0b40df5f"
      url "https://github.com/arran4/rotatingcircles/releases/download/v#{version}/rotatingcircles_Linux_arm64.tar.gz"
    end
  end

  name "rotatingcircles"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rotatingcircles"

  # No zap stanza required

end
