# This file was generated by GoReleaser. DO NOT EDIT.
cask "sentencestats" do
  name "sentencestats"
  desc ""
  homepage ""
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sentencestats"

  on_macos do
    on_intel do
      url "https://github.com/arran4/sentencestats/releases/download/v#{version}/sentencestats_#{version}_darwin_amd64.tar.gz"
      sha256 "16143ed2952b30f9fd6fc83b26297d0b75deab107576b420812d2a03ada3e1fb"
    end
    on_arm do
      url "https://github.com/arran4/sentencestats/releases/download/v#{version}/sentencestats_#{version}_darwin_arm64.tar.gz"
      sha256 "60424717edbbf437875630a36c4f0b0c4cd7dd87277fbca5012d572b2cea84bb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/sentencestats/releases/download/v#{version}/sentencestats_#{version}_linux_amd64.tar.gz"
      sha256 "0d1b7088b1e738b43f6ae72c9b48d7baf74860ee94315517295e008c534ba35f"
    end
    on_arm do
      url "https://github.com/arran4/sentencestats/releases/download/v#{version}/sentencestats_#{version}_linux_arm64.tar.gz"
      sha256 "9738d5c88c9bc2193f01c5bf8e52b43f3c35fdcc41ccc477ac5e99b387a0052f"
    end
  end

  # No zap stanza required
end
