# This file was generated by GoReleaser. DO NOT EDIT.
cask "sentencestats" do
  version "0.0.8"

  on_macos do
    on_intel do
      url "https://github.com/arran4/sentencestats/releases/download/v#{version}/sentencestats_#{version}_darwin_amd64.tar.gz"
      sha256 "aac1d2fe5e50a9e271fe47f133bd9078632108e9ddbf43d01ef96a985d9ffbbc"
    end
    on_arm do
      url "https://github.com/arran4/sentencestats/releases/download/v#{version}/sentencestats_#{version}_darwin_arm64.tar.gz"
      sha256 "45f1c5bf5e8473974c0037bdb059c989e764b12da2969e5ce44ebbc7ddda951f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/sentencestats/releases/download/v#{version}/sentencestats_#{version}_linux_amd64.tar.gz"
      sha256 "9f2b7a5cb42e9eec0a5d1d7fb4d650840239dd4e0e78ae4639fb439cfe20ed26"
    end
    on_arm do
      url "https://github.com/arran4/sentencestats/releases/download/v#{version}/sentencestats_#{version}_linux_arm64.tar.gz"
      sha256 "9deb3c8a7243b72dc704f05835c44a79f8f7526116166574e26b9abe48de9564"
    end
  end

  name "sentencestats"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sentencestats"

  # No zap stanza required

end
