# This file was generated by GoReleaser. DO NOT EDIT.
cask "g2" do
  name "g2"
  desc ""
  homepage ""
  version "0.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "g2"

  on_macos do
    on_intel do
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_darwin_amd64.tar.gz"
      sha256 "5c2ec79be8c6150569fa28c0558838563780dc3a1a6b27db22419fbc7048f939"
    end
    on_arm do
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_darwin_arm64.tar.gz"
      sha256 "872f9370f1f22837ef580fd023d45835f7a0339fb20559b82b12d5d67c8fb209"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_linux_amd64.tar.gz"
      sha256 "bea11400df39547ae8371271770c147636468c88272ba5e644a9b0da56189544"
    end
    on_arm do
      url "https://github.com/arran4/g2/releases/download/v#{version}/g2_#{version}_linux_arm64.tar.gz"
      sha256 "86d2a7c2f842c2f7d143ccab7d1c87bab3a8e0104369f105b3e57389f67caf08"
    end
  end

  # No zap stanza required
end
